apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2022-10-12T16:22:33Z'
  generation: 6
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2022-10-12T16:22:33Z'
  name: patternfly-frontend-build
  namespace: pf
  resourceVersion: '986950'
  uid: a37e78fb-f96d-4854-8ec6-c30ba8d2f64d
spec:
  params:
    - default: 'https://github.com/mmartofel/patternfly-frontend-starter'
      description: Patternfly git repo location
      name: pf-frontend-git-repo
      type: string
    - default: main
      description: Patternfly git repo branch
      name: pf-frontend-git-branch
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/pf/patternfly-frontend-starter
      description: Image destination
      name: pf-image-destination
      type: string
  tasks:
    - name: pf-frontend-repo-clone
      params:
        - name: url
          value: $(params.pf-frontend-git-repo)
        - name: revision
          value: $(params.pf-frontend-git-branch)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:cadf614a6044ee37397de3abe7674827ecab225e7fac9fb123eff5473e2c4003
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pf-frontend-git-source
    - name: pf-buildah-frontend-image
      params:
        - name: IMAGE
          value: '$(params.pf-image-destination):$(params.pf-frontend-git-branch)'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - pf-frontend-repo-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: pf-frontend-git-source
    - name: pf-new-app
      params:
        - name: SCRIPT
          value: 'oc new-app patternfly-frontend-starter:main'
        - name: VERSION
          value: latest
      runAfter:
        - pf-buildah-frontend-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: pf-expose-service
      params:
        - name: SCRIPT
          value: oc expose service/patternfly-frontend-starter
        - name: VERSION
          value: latest
      runAfter:
        - pf-new-app
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: pf-frontend-git-source

