kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: pf
  labels:
    kubernetes.io/metadata.name: pf
    openshift-pipelines.tekton.dev/namespace-reconcile-version: 1.8.0
    openshift.io/description: ''
    openshift.io/display-name: ''
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
