kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pf-source-pv
  namespace: pf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-premium
  volumeMode: Filesystem

